#!/usr/bin/env python3

import csv
import json
import re
from sys import argv

import timer
import config
import display

file_path = argv[0].split("//")[0]

arguments = {
    "total": {
        "switch": "--total",
        "flag": "t",
        "value": False
    },
    "help": {
        "switch": "--help",
        "flag": "h",
        "value": False
    },
    "getconfig": {
        "switch": "--getconfig",
        "flag": "g",
        "value": False
    },
    "setconfig": {
        "switch": "--setconfig",
        "flag": "s",
        "value": False
    }
}


def flatten(li):
    if li == []:
        return li
    if type(li[0]) == list:
        return flatten(li[0]) + flatten(li[1:])
    return li[:1] + flatten(li[1:])


def get_flags():
    flags = re.findall(r"\s(-[a-zA-Z]+)", " ".join(argv))
    for ind, flag in enumerate(flags):
        del(argv[argv.index(flag)])
        flags[ind] = list(flag[1:])
    return flatten(flags)


def get_switches():
    switches = re.findall(r"\s(--[a-zA-Z]+)", " ".join(argv))
    for ind, switch in enumerate(switches):
        del(argv[argv.index(switch)])
    return flatten(switches)


def process_all_args(arugments):
    flags = get_flags()
    switches = get_switches()
    for var, arg in arguments.items():
        if arg["flag"] in flags:
            arg["value"] = True
            del(flags[flags.index(arg["flag"])])
        if arg["switch"] in switches:
            arg["value"] = True
            del(switches[switches.index(arg["switch"])])
    return ["-" + flag for flag in flags] + switches


if __name__ == "__main__":

    unrecognised = process_all_args(arguments)
    if len(argv) > 2:
        unrecognised += argv[2:]

    if unrecognised:
        unrecognised = " ".join(unrecognised)
        print(f"tracker: unrecognised option(s) '{unrecognised}'")
        exit("Try 'tracker --help' for more information")

    task = argv[1] if len(argv) == 2 else config.default_task

    if arguments["help"]["value"]:
        with open(f"{file_path}/.usage.txt", "r") as usage:
            print(usage.read())
        exit()

    if arguments["total"]["value"]:
        try:
            with open(f"{config.csv_path}/{task}.csv", "r") as csvfile:
                taskreader = csv.DictReader(csvfile)
                for row in taskreader:
                    last_task = row
                total = last_task["Total"]
                exit(f"Total time in {task}: {total}")
        except IOError:
            exit(f"Task not found: '{task}'")

    if arguments["getconfig"]["value"]:
        print(f"default-task: {config.default_task}")
        print(f"csv-path: {config.csv_path}")
        print(f"autosave-delay: {config.autosave_delay}")
        print(f"autosave-q: {config.autosave_q}")
        print(f"autosave-c: {config.autosave_c}")
        exit()
    
    if arguments["setconfig"]["value"]:
        default_task = input(f"default-task: ") or config.default_task
        csv_path = input(f"csv-path: ") or config.csv_path
        autosave_delay = input(f"autosave-delay: ") or timer.format_time(config.autosave_delay)
        autosave_q = input(f"autosave-q: ") or str(config.autosave_q)
        autosave_q = False if autosave_q.lower() == "false" else True
        autosave_c = input(f"autosave-c: ") or str(config.autosave_c)
        autosave_c = False if autosave_c.lower() == "false" else True
        with open(f"{file_path}/config.json", "w+") as config_file:
            content = json.dumps(
                {
                    "default-task": default_task,
                    "csv-path": csv_path,
                    "autosave-delay": autosave_delay,
                    "autosave-q": autosave_q,
                    "autosave-c": autosave_c
                }
            )
            config_file.write(content)
        exit()

    feeder = display.Feeder(task)
    feeder.run()
