#!/usr/bin/env python3

from sys import argv
import csv

import config
import display

arguments = {
    "total": {
        "switch": "--total",
        "flag": "-t",
        "value": False
    }
}

def process_arg(arg, arg_type):
    if arg[arg_type] in argv:
        arg["value"] = True
        del(argv[argv.index(arg[arg_type])])

def process_all_args(arguments):
    for var, arg in arguments.items():
        process_arg(arg, "switch")
        process_arg(arg, "flag")


if __name__ == "__main__":

    process_all_args(arguments)

    if len(argv) > 2:
        unrecognised = " ".join(argv[2:])
        exit(f"tracker: unrecognised option(s) '{unrecognised}'")

    task = argv[1] if len(argv) == 2 else config.default_task

    if arguments["total"]["value"]:
        try:
            with open(f"{config.csv_path}/{task}.csv", "r") as csvfile:
                taskreader = csv.DictReader(csvfile)
                for row in taskreader:
                    last_task = row
                total = last_task["Total"]
                exit(f"Total time in {task}: {total}")
        except IOError:
            exit(f"Task not found: '{task}'")
            

    feeder = display.Feeder(task)
    feeder.run()
